name: placeholder_Name

on:
  pull_request:
    branches: 
      - branch-name
  push:
    branches:
      - branch-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8'] # Corrected Java version
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin' # Using Temurin as an example; adjust as needed
        cache: maven

    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

    - name: Run tests
      run: mvn test
