name: Java CI with Elasticsearch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports:
          - 9200:9200
        options: >-
          -e "discovery.type=single-node"
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure Elasticsearch
      run: |
        sudo rm -rf /var/lib/elasticsearch
        curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb -o elasticsearch.deb
        sudo dpkg -i --force-confnew elasticsearch.deb
        sudo cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
        sudo cat /etc/elasticsearch/elasticsearch.yml
        sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
        sudo service elasticsearch start
        sleep 30

    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

    - name: Run tests
      run: |
        ulimit -a
        mvn test
