name: placeholder_Name

on:
  pull_request:
    branches: 
      - branch-name
  push:
    branches:
      - branch-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['1.8'] # Define the Java versions as a list
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up JDK
      uses: actions/setup-java@v2 
      with:
        java-version: ${{ matrix.java-version }} 
        distribution: 'temurin' 
        cache: maven 

    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
