name: Java CI with Elasticsearch

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports:
          - 9200:9200
        options: >-
          -e "discovery.type=single-node"
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

    - name: Run tests (allowing failures)
      run: mvn test || true
     
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      if: always() 
      with:
        name: surefire-reports
        path: target/surefire-reports

